dl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
if(!file.exists('data.zip')) {download.file(dl, destfile = 'data.zip', method = 'curl')}
unzip('data.zip')
list.files()

library(dplyr)
library(readr)
library(lubridate)
library(ggplot2)
library(ggprism)

scc <- read_rds("Source_Classification_Code.rds")
pm25 <- read_rds("summarySCC_PM25.rds")
file.remove(c("data.zip","Source_Classification_Code.rds", "summarySCC_PM25.rds"))

head(scc)
sapply(scc, class)
scc <- scc %>% mutate_at(c(1,3,4), as.character)
head(pm25)
sapply(pm25, class)

coal <- scc %>% filter(grepl('coal', Short.Name,ignore.case = TRUE)) %>% select(SCC)
pm25_coal<- pm25 %>% filter(SCC %in% coal[['SCC']])
pm25_coal <- pm25_coal %>% group_by(year) %>% summarize(Emissions = sum(Emissions))
pm25_coal$year <- as.factor(pm25_coal$year)

##plotting with base plot
png(file = 'plot4.png', width = 480, height = 480)
with(pm25_coal, plot(x=year, y=Emissions, pch = 19, col = 'steelblue',
                     xlab = 'Year', ylab = 'Total PM2.5 Emission',
                     main = expression('Total' ~PM[2.5]~ 'generated by Coal Combustion'), xaxt = 'n'))
lines(pm25_coal$year, pm25_coal$Emissions, col = 'steelblue')
axis(1, at = pm25_coal$year, labels = pm25_coal$year)
dev.off()

##plotting with ggplot
theme_set(theme_bw())
ggplot(pm25_coal, aes(year, Emissions, group =1)) +
  geom_point(color = 'cyan4', size = 3) + geom_line(color = 'cyan4') +
  ggtitle(expression('Total' ~PM[2.5]~ 'generated by Coal Combustion')) +
  labs(x='Year', y = 'Total PM2.5 Emission') +
  theme(plot.title = element_text(hjust = 0.5), aspect.ratio = 1/1)
ggsave('plot4.png')




